### ISSUE TITLE
Stuck when running python test.py --config config/rfs_phase2_scannet.yaml

### ISSUE THREAD

**Issue by saladcat** [ashawkey/dimr#3]
logging as following 
```
[BSP] generating mesh 14 / 16 | chair | z = 0.2947016954421997
[BSP] generating mesh 15 / 16 | display | z = 0.29926255345344543
WARNING - 2022-08-31 11:13:16,860 - sample - only got 1923/2048 samples!
WARNING - 2022-08-31 11:13:17,950 - sample - only got 1282/2048 samples!
WARNING - 2022-08-31 11:13:18,048 - sample - only got 1147/2048 samples!
WARNING - 2022-08-31 11:13:18,771 - sample - only got 1440/2048 samples!
WARNING - 2022-08-31 11:13:19,764 - sample - only got 1350/2048 samples!
WARNING - 2022-08-31 11:13:19,813 - sample - only got 1274/2048 samples!
WARNING - 2022-08-31 11:13:19,851 - sample - only got 1746/2048 samples!
WARNING - 2022-08-31 11:13:19,895 - sample - only got 2028/2048 samples!
WARNING - 2022-08-31 11:13:19,986 - sample - only got 1628/2048 samples!
WARNING - 2022-08-31 11:13:20,613 - sample - only got 1719/2048 samples!
WARNING - 2022-08-31 11:13:20,655 - sample - only got 1897/2048 samples!
WARNING - 2022-08-31 11:13:20,753 - sample - only got 1522/2048 samples!
[Mesh] save 0 / 16, label = chair
[Mesh] save 1 / 16, label = sofa
[Mesh] save 2 / 16, label = display
[Mesh] save 3 / 16, label = chair
[Mesh] save 4 / 16, label = bookshelf
[Mesh] save 5 / 16, label = chair
[Mesh] save 6 / 16, label = display
[Mesh] save 7 / 16, label = sofa
[Mesh] save 8 / 16, label = trash_bin
[Mesh] save 9 / 16, label = table
[Mesh] save 10 / 16, label = trash_bin
[Mesh] save 11 / 16, label = chair
[Mesh] save 12 / 16, label = trash_bin
[Mesh] save 13 / 16, label = table
[Mesh] save 14 / 16, label = chair
[Mesh] save 15 / 16, label = display
[2022-08-31 11:13:21,015  INFO  test.py  line 160  3479014]  instance iter: 2/311 point_num: 195084 ncluster: 16 time: total 11.51s inference 11.28s save 0.23s
INFO - 2022-08-31 11:13:21,015 - test - instance iter: 2/311 point_num: 195084 ncluster: 16 time: total 11.51s inference 11.28s save 0.23s
```

When I interrupted by ctrl+C, it shows that there is an exception in data acquisition
```
^CTraceback (most recent call last):
  File "test.py", line 197, in <module>
    test(model, model_fn, data_name, cfg.test_epoch)
  File "test.py", line 62, in test
    for i, batch in enumerate(dataloader):
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1138, in _get_data
    success, data = self._try_get_data()
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/home/zsy/anaconda3/envs/dimr/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
^C
```

What could be the reason for this? Is my data incomplete?

**Comment by ashawkey** [comment]
It seems a multi-threading problem from pytorch data loader. Could you try to set the `num_workers` to 0 and try again (e.g., from [here](https://github.com/ashawkey/dimr/blob/main/config/rfs_phase2_scannet.yaml#L32))? Or maybe you can upgrade the pytorch version.

**Comment by saladcat** [comment]
> It seems a multi-threading problem from pytorch data loader. Could you try to set the `num_workers` to 0 and try again (e.g., from [here](https://github.com/ashawkey/dimr/blob/main/config/rfs_phase2_scannet.yaml#L32))? Or maybe you can upgrade the pytorch version.

fixed it by set `num_workers` to 0, thx!
